### ISSUE TITLE
License File?

### ISSUE THREAD

**Issue by owaaa** [cnorthwood/ternip#23]
What license is this released under?

**Comment by cnorthwood** [comment]
That is a very good question. As I created this as party of my MSc thesis, I think copyright belongs to the university rather than me... I will check and get back to you. If it's up to me, I'd choose Apache 2.0

**Comment by cnorthwood** [comment]
@leondz - do you know what the situation is? (and would you be able to ask the department if I can release this under an open-source license?)

Thanks

**Comment by leondz** [comment]
There's no problem from the uni releasing this iff it's under an open-source license; I think we spoke about LGPL or Apache at the time. In fact, they have since taken the policy of (a) retaining all IP ownership and copyright on new theses etc; (b) publishing everything under CC! So, I guess the sole issue is choosing a license, and modifying the code conform to & possible also include the text of that license.
